modLoader = "javafml"
loaderVersion = "[37,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "mossfix"
version = "${version}"
displayName = "Moss Fix"
authors = "Gamma_02"
description = '''
Highly configurable (or will be) server-side mod that fixes moss by allowing spread under transparent blocks
'''
logoFile = "icon.png"

[[dependencies.mossfix]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mossfix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"
