modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "moss-fix"
version = "${version}"
displayName = "Moss FIx"
authors = "Gamma_02"
description = '''
Highly configurable server-side mod that fixes moss by allowing spread under transparent blocks
'''
logoFile = "assets/moss-fix/icon.png"

[[dependencies.moss-fix]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moss-fix]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "moss-fix.mixins.json"
