modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "mossfix"
version = "${version}"
displayName = "Moss Fix"
authors = "Gamma_02"
description = '''
Highly configurable (or will be) server-side mod that fixes moss by allowing spread under transparent blocks
'''
logoFile = "assets/mossfix/icon.png"

[[dependencies.mossfix]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mossfix]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "moss_fix.mixins.json"
